### ISSUE TITLE
opx-ethtool doesn't provide speed info

### ISSUE THREAD

**Issue by deltasierra** [open-switch/opx-nas-interface#21]
`root@l2:~# opx-ethtool -e e101-001-0
Show media info for e101-001-0
Key: 2.28.1835221.1835077.1835078.1835079.
base-pas/media/rate-identifier = 0
base-pas/media/oper-status = 0
base-pas/media/category = 2
`

`root@l2:~# opx-ethtool -s e101-049-0`
`root@l2:~#`

^ No information returned

`root@l2:~# opx-show-version`
`OS_NAME="OPX-Base-Dell"`
`OS_VERSION="2.1.0"`
`PLATFORM=""`
`ARCHITECTURE="x86_64"`
`INTERNAL_BUILD_ID="OpenSwitch Base Blue Print 1.0.0"`
`BUILD_VERSION="2.1.0(26)"`
`BUILD_DATE="2017-07-14T23:29:12+0000"`
`INSTALL_DATE="2017-08-05T16:57:21+0000"`
`SYSTEM_UPTIME= 1 week, 1 day, 7 hours, 9 minutes`
`SYSTEM_STATE= running`
`UPGRADED_PACKAGES=no`
`ALTERED_PACKAGES=no`

**Comment by GarrickHe** [comment]
Hello @deltasierra,
I'll take a look at this issue.

**Comment by GarrickHe** [comment]
Hello @deltasierra 
This issue has been resolved. When you use the -s option along with an interface, Linux ethtool reports no information as well. To lessen user confusion, it is now mandatory in opx-ethtool to pass the devname along with at least one of the three options you want to adjust (speed, autoneg, duplex). If you pass just opx-ethtool -s <devnam>, the help message will appear.

hope this helps,
Garrick
