### ISSUE TITLE
Unable to verify MTU via ip link or ip addr

### ISSUE THREAD

**Issue by deltasierra** [open-switch/opx-nas-interface#23]
Neither method used in documentation to view interface MTU are working.  

Config guide uses `ip link show`
Dev guide uses `ip addr show`

Neither seem to return information info to verify MTU
![s2-172 16 53 90 - securecrt 2017-10-22 14-20-29](https://user-images.githubusercontent.com/4925805/31865477-1bd3e41a-b735-11e7-9786-c137ba3bb0f8.png)

```
admin@s6000-r2r7-u28-spine2:~$ cat /etc/OPX-release-version 
OS_NAME="OPX"
OS_VERSION="2.1.0"
PLATFORM="S6000-ON"
ARCHITECTURE="x86_64"
INTERNAL_BUILD_ID="OpenSwitch blueprint for Dell 1.0.0"
BUILD_VERSION="2.1.0(0)"
BUILD_DATE="2017-08-04T12:01:19-0700"
INSTALL_DATE="2017-10-10T22:28:50+0000"
```
@Ragsboss

**Comment by madhu222** [comment]
@deltasierra Did you fanout the port e101-028-0? It is showing fine for me

root@OPX:/etc/dhcp/dhclient-exit-hooks.d# ip link show e101-028-0
25: e101-028-0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether ec:f4:bb:fd:52:5a brd ff:ff:ff:ff:ff:ff
    alias NAS## 0 85

**Comment by deltasierra** [comment]
no fanouts.  This is happening on every ports.  

```

**Comment by deltasierra** [comment]
@madhu222 you can close this.  This is related a namespace issue.  Sorry for the report.  

running `sudo ip netns exec default bash` fixes this.
