### ISSUE TITLE
Interface IPv6 disabled when added to a VLAN

### ISSUE THREAD

**Issue by james-jra** [open-switch/opx-nas-interface#25]
## Interface IPv6 disabled when added to a VLAN ##

When an interface is added to a VLAN as a tagged or untagged port, its IPv6
configuration is set to "disabled", and any configured IPv6 addresses on that
interface are lost.

I can manually enable IPv6 using CPS once in this state, but adding VLAN configuration should not affect the IPv6 configuration.

This same behaviour occurs with both cps_config_vlan.py and native Linux
networking utilities (brctl, ip link, ip addr etc.) which is why I've raised this issue against opx-nas-inteface instead of opx-cps. If you think this issue belongs elsewhere, I'm happy to move it.

The same behaviour does not occur with IPv4 addresses or on non-opx machines.
Manually bringing the interfaces up does not fix this.

## Reproduction ##

* Start with a system with an oper-up interface.
* Validate that is has an IPv6 address, or configure one on it. 
```
opxUser@opx221_vm:~$ ip addr show dev e101-002-0
13: e101-002-0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 08:00:27:2d:78:a2 brd ff:ff:ff:ff:ff:ff
    inet 172.28.128.4/24 brd 172.28.128.255 scope global e101-002-0
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe2d:78a2/64 scope link
       valid_lft forever preferred_lft forever
```
* CPS shows that IPv6 is enabled on this interface:
```
opxUser@opx221_vm:~$ sudo cps_get_oid.py base-ip/ipv6 base-ip/ipv6/name=e101-002-0

============1.22.1441815.1441805.==========
base-ip/ipv6/address/prefix-length = 64
base-ip/ipv6/address/ip = fe800000000000000a0027fffe2d78a2
base-ip/ipv6/forwarding = 1
base-ip/ipv6/name = e101-002-0
base-ip/ipv6/vrf-id = 0
base-ip/ipv6/autoconf = 1
base-ip/ipv6/enabled = 1            <-------------
base-ip/ipv6/ifindex = 13
------------------------------------------------
```
* Use the CPS utility to configure a VLAN using this interface. (To use native Linux utilities, see the "Linux VLAN configuration" section of this report).
```
opxUser@opx221_vm:~$ sudo cps_config_vlan.py --add --id 100 --vlantype 1 -port e101-002-0 --tagged
Success
```
* The IPv6 address on the interface is now gone
```
opxUser@opx221_vm:~$ ip addr show dev e101-002-0
13: e101-002-0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 08:00:27:2d:78:a2 brd ff:ff:ff:ff:ff:ff
    inet 172.28.128.4/24 brd 172.28.128.255 scope global e101-002-0
       valid_lft forever preferred_lft forever
```
* And we can't configure another one on the interface or the VLAN sub-interface
```
opxUser@opx221_vm:~$ sudo ip addr add fd77:6bad:cb49:9cee::1/64 dev e101-002-0
RTNETLINK answers: Permission denied
opxUser@opx221_vm:~$ sudo ip addr add fd77:6bad:cb49:9cee::1/64 dev e101-002-0.100
RTNETLINK answers: Permission denied
```
* CPS shows that IPv6 is disabled on this interface and the VLAN sub-interface
```
opxUser@opx221_vm:~$ sudo cps_get_oid.py base-ip/ipv6 base-ip/ipv6/name=e101-002-0

============1.22.1441815.1441805.==========
base-ip/ipv6/forwarding = 1
base-ip/ipv6/name = e101-002-0
base-ip/ipv6/vrf-id = 0
base-ip/ipv6/autoconf = 1
base-ip/ipv6/enabled = 0       <-------------
base-ip/ipv6/ifindex = 13
------------------------------------------------
opxUser@opx221_vm:~$ sudo cps_get_oid.py base-ip/ipv6 base-ip/ipv6/name=e101-002-0.100

============1.22.1441815.1441805.==========
base-ip/ipv6/forwarding = 1
base-ip/ipv6/name = e101-002-0.100
base-ip/ipv6/vrf-id = 0
base-ip/ipv6/autoconf = 1
base-ip/ipv6/enabled = 0      <---------------
base-ip/ipv6/ifindex = 48
------------------------------------------------
```
* However we CAN still configure IPv4
```
opxUser@opx221_vm:~$ sudo ip addr add 10.100.10.2/24 dev e101-002-0
opxUser@opx221_vm:~$ ip addr show dev e101-002-0
13: e101-002-0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 08:00:27:2d:78:a2 brd ff:ff:ff:ff:ff:ff
    inet 172.28.128.4/24 brd 172.28.128.255 scope global e101-002-0
       valid_lft forever preferred_lft forever
    inet 10.100.10.2/24 scope global e101-002-0
       valid_lft forever preferred_lft forever
```
* After reverting this VLAN configuration, IPv6 is enabled once again
```
opxUser@opx221_vm:~$ sudo cps_config_vlan.py --del --name br100
Success
opxUser@opx221_vm:~$ sudo cps_get_oid.py base-ip/ipv6 base-ip/ipv6/name=e101-002-0

============1.22.1441815.1441805.==========
base-ip/ipv6/address/prefix-length = 64
base-ip/ipv6/address/ip = fe800000000000000a0027fffe2d78a2
base-ip/ipv6/forwarding = 1
base-ip/ipv6/name = e101-002-0
base-ip/ipv6/vrf-id = 0
base-ip/ipv6/autoconf = 1
base-ip/ipv6/enabled = 1      <-------------
base-ip/ipv6/ifindex = 13
------------------------------------------------
```

### Linux VLAN configuration ###

This is the same configuration we tested using Linux instead of CPS:

* Create the bridge
```
sudo brctl addbr br100
```
* Create the subinterface
```
sudo ip link add link e101-002-0 name e101-002-0.100 type vlan id 100
```
* Add the subinterface
```
sudo brctl addif br100 e101-002-0.100
```

**Comment by atanu-mandal** [comment]
Hi @james-jra , this behavior seems to be expected as per the current implementation. 

Please refer 
https://github.com/open-switch/opx-nas-linux/blob/be164dcc5e9e65193d72e8fae80e976b22949d8b/src/if/os_interface_vlan.cpp#L50

When interface is added to a VLAN it should be in L2 mode. So before adding an interface to a VLAN we should  also flush  if any ip address configured (ip addr flush dev <interface name>).
When it is removed from a VLAN it again goes to back L3 mode (default mode).

Regarding ipv4 address configuration, it should  reject the configuration at NPU level (which is not happening) as it does for vlan sub interfaces (e.g. e101-002-0.100). We will look into this.

**Comment by james-jra** [comment]
Thanks @atanu-mandal, I understand this behaviour.

But in general, it seems strange that configuration for a VLAN interface can affect the IP configuration for another interface. It would be better for the transaction to fail unless the [un]tagged ports were in L2 mode.

Until now the configuration model for CPS has been declarative: what you “set” in CPS is reflected in the target configuration. The above behaviour does not do this - one part of the target configuration is updated *as a side-effect* of a change to a completely separate object.

This would be much better as an RPC, and CPS already has examples of this. For example: when configuring interface fanout, it's an RPC which creates the logical interfaces. They do not just "appear" as a result of setting a port's breakout mode.

What do you think?
