### ISSUE TITLE
"cps_config_vlan.py --del" fails to delete the bridge vlan

### ISSUE THREAD

**Issue by Ragsboss** [open-switch/opx-nas-interface#27]
See below

```
root@rack-3-leaf-1:/var/log# cps_config_vlan.py --del --name br300
Failed
```

The bridge br300 was created using `brctl addbr br300`. Then from `/var/log/syslog` I find
```
Apr  4 19:46:32 Rack-3-Leaf-1 opx_nas_daemon[554]: [INTERFACE:NAS-COM-INT-SET], No interface name or index passed to process common interface set request
Apr  4 19:46:32 Rack-3-Leaf-1 python[439]: [DSAPI:COMMIT], Failed to commit request at 0 out of 1
Apr  4 19:46:32 Rack-3-Leaf-1 python[439]: Failed to commit request
Apr  4 19:46:32 Rack-3-Leaf-1 python[26585]: [DSAPI:COMMIT], Failed to commit request at 0 out of 1
```

That bridge does appear in show
```
root@rack-3-leaf-1:/var/log# cps_config_vlan.py --show
Key: 1.19.44.2883617.2883612.2883613.
dell-base-if-cmn/if/interfaces/interface/if-index = 63
dell-if/if/interfaces/interface/phys-address = 34:17:eb:f4:f3:8d
dell-if/if/interfaces/interface/untagged-ports = e101-042-0,e101-040-0,e101-038-0,e101-036-0,e101-035-0,e101-034-0,e101-033-0,e101-032-0,e101-031-0,e101-030-0,e101-029-0,e101-028-0,e101-026-0,e101-012-0,e101-008-0,e101-009-0,e101-007-0,e101-006-0,e101-005-0,e101-004-0,e101-003-0,e101-002-0,e101-001-0,e101-014-0,e101-015-0,e101-016-0,e101-017-0,e101-018-0,e101-019-0,e101-020-0,e101-021-0,e101-022-0,e101-023-0,e101-024-0,e101-025-0
base-if-vlan/if/interfaces/interface/id = 500
if/interfaces/interface/name = br500
dell-if/if/interfaces/interface/vlan-type = 1
dell-if/if/interfaces/interface/learning-mode = 1
dell-if/if/interfaces/interface/mtu = 1532
if/interfaces/interface/enabled = 0
Key: 1.19.44.2883617.2883612.2883613.
dell-base-if-cmn/if/interfaces/interface/if-index = 62
dell-if/if/interfaces/interface/phys-address = 
base-if-vlan/if/interfaces/interface/id = 0
if/interfaces/interface/name = br1000
dell-if/if/interfaces/interface/vlan-type = 0
dell-if/if/interfaces/interface/learning-mode = 1
dell-if/if/interfaces/interface/mtu = 1532
if/interfaces/interface/enabled = 0
Key: 1.19.44.2883617.2883612.2883613.
dell-base-if-cmn/if/interfaces/interface/if-index = 61
dell-if/if/interfaces/interface/phys-address = 
base-if-vlan/if/interfaces/interface/id = 0
if/interfaces/interface/name = br300
dell-if/if/interfaces/interface/vlan-type = 0
dell-if/if/interfaces/interface/learning-mode = 1
dell-if/if/interfaces/interface/mtu = 1532
if/interfaces/interface/enabled = 0
root@rack-3-leaf-1:/var/log# 
```

And in brctl and ip link
```
root@rack-3-leaf-1:/var/log# brctl show
bridge name	bridge id		STP enabled	interfaces
br1000		8000.000000000000	no		
br300		8000.000000000000	no		

...
61: br300: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default 
    link/ether 96:e5:22:cf:68:cd brd ff:ff:ff:ff:ff:ff
62: br1000: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default 
    link/ether 32:45:a9:39:4b:ef brd ff:ff:ff:ff:ff:ff

```

My opx version is
```
root@rack-3-leaf-1:/var/log# opx-show-version 
OS_NAME="OPX"
OS_VERSION="2.2.1"
PLATFORM="S4048-ON"
ARCHITECTURE="x86_64"
INTERNAL_BUILD_ID="OpenSwitch blueprint for Dell 1.0.0"
BUILD_VERSION="2.2.1.0"
BUILD_DATE="2018-02-13T13:48:47-0800"
INSTALL_DATE="2018-02-23T04:36:13+0000"
SYSTEM_UPTIME= 5 weeks, 5 days, 14 hours, 57 minutes
SYSTEM_STATE= running
UPGRADED_PACKAGES=no
ALTERED_PACKAGES=no
root@rack-3-leaf-1:/var/log# 
```

cc: @vnam1

**Comment by atanu-mandal** [comment]
Hi @Ragsboss , I have just tried this using OPX 2.3.0 and everything seems to be working as expected. Please refer below...

root@OPX:#**brctl addbr br111**
root@OPX:#**brctl show**
root@OPX:# **brctl show**
bridge name     bridge id               STP enabled     interfaces
br111           8000.000000000000       no

root@OPX:#**cps_get_oid.py -qua target dell-base-if-cmn/if/interfaces/interface if/interfaces/interface/name=br111**
root@OPX:#**ip addr flush dev e101-011-0**
root@OPX:#**ip link add link e101-011-0 name e101-011-0.111 type vlan id 111**
root@OPX:# **brctl show**
bridge name     bridge id               STP enabled     interfaces
br111           8000.000000000000       no

root@OPX:#**cps_get_oid.py -qua target dell-base-if-cmn/if/interfaces/interface if/interfaces/interface/name=br111**
root@OPX:#**brctl addif br111 e101-011-0.111**
root@OPX:#**brctl show**
bridge name     bridge id               STP enabled     interfaces
br111           8000.141877950357       no              e101-011-0.111

root@OPX:#**cps_get_oid.py -qua target dell-base-if-cmn/if/interfaces/interface if/interfaces/interface/name=br111**
============dell-base-if-cmn/if/interfaces/interface==========
dell-base-if-cmn/if/interfaces/interface/if-index = 46
dell-if/if/interfaces/interface/phys-address = 14:18:77:95:03:57
if/interfaces/interface/type = ianaift:l2vlan
base-if-vlan/if/interfaces/interface/id = 111
if/interfaces/interface/name = br111
dell-if/if/interfaces/interface/vlan-type = 0
dell-if/if/interfaces/interface/learning-mode = 1
dell-if/if/interfaces/interface/mtu = 1532
if/interfaces/interface/enabled = 0
dell-if/if/interfaces/interface/tagged-ports = e101-011-0


root@OPX:#**opx-switch-shell "vlan show"**
vlan 1  ports none (0x0000000000000000000000000000000000000000000000000000000000000000), untagged none (0x0000000000000000000000000000000000000000000000000000000000000000) MCAST_FLOOD_UNKNOWN
vlan 111        ports xe10 (0x0000000000000000000000000000000000000000000000000000020000000000), untagged none (0x0000000000000000000000000000000000000000000000000000000000000000) MCAST_FLOOD_UNKNOWN
vlan 4095       ports xe (0x00000000000000000000000000000000000001e222222222223e222222222222), untagged xe (0x00000000000000000000000000000000000001e222222222223e222222222222) MCAST_FLOOD_UNKNOWN

root@OPX:#**cps_config_vlan.py --del --name br111**
Success
root@OPX:#**opx-switch-shell "vlan show"**
vlan 1  ports none (0x0000000000000000000000000000000000000000000000000000000000000000), untagged none (0x0000000000000000000000000000000000000000000000000000000000000000) MCAST_FLOOD_UNKNOWN
vlan 4095       ports xe (0x00000000000000000000000000000000000001e222222222223e222222222222), untagged xe (0x00000000000000000000000000000000000001e222222222223e222222222222) MCAST_FLOOD_UNKNOWN
root@OPX:#**cps_get_oid.py -qua target dell-base-if-cmn/if/interfaces/interface if/interfaces/interface/name=br111**
root@OPX:#**brctl show**
bridge name     bridge id               STP enabled     interfaces

root@OPX:# **opx-show-version**
OS_NAME="OPX"
OS_VERSION="2.3.0"
PLATFORM="S6010-ON"
ARCHITECTURE="x86_64"
INTERNAL_BUILD_ID="OpenSwitch blueprint for Dell 1.0.0"
BUILD_VERSION="2.3.0.0"
BUILD_DATE="2018-03-27T20:07:19-0700"
INSTALL_DATE="2018-04-05T06:23:17+0000"
SYSTEM_UPTIME= 2 hours, 16 minutes
SYSTEM_STATE= running
UPGRADED_PACKAGES=no
ALTERED_PACKAGES=no

Thanks,
-Atanu
