### ISSUE TITLE
Question on disabled ports on Z9100-ON

### ISSUE THREAD

**Issue by vnam1** [open-switch/opx-nas-interface#35]
I have found this info on Z9100-ON:

"
    The system can only handle 128 logical ports.
    This means that if all 32 QSFP28 ports are broken out into
    4x25G or 4x10G mode, the two 10G ports (33 and 34) must be
    set to "disabled".
"
When I did breakout of 32 100g ports into 4x10 or 4x25 totaling 128+2, I did not
see any indication from opx-ethtool that ports 33 and 34 are disabled.
So my question is:
1. How to find if a port is disabled?
2. After these 2 10g ports (33 and 34) get disabled because of > 128 logical ports, if I unsplit a 100g port from 4x10 to 100g will these ports (33, 34) will get enabled automatically or do I need to do anything?

**Comment by nchervela** [comment]
@vnam1 Can you share the output of "hshell -c ps" on your system?  with the breakout configuration that you mentioned.

**Comment by nchervela** [comment]
@vnam1 Z9100 supports 130 ports. The documentation needs to be fixed.  To check whether a port is disabled, pls check the 'ena/link' column of the above output.  For disabled ports, it should show as “!ena”. In the above output, all 130 ports are enabled.

**Comment by jeff-yin** [comment]
@vnam1 I'll close this for now. Feel free to re-open or create a new one if you have any followup.
