### ISSUE TITLE
OPX 3.0.0 does not bring interfaces up after reboot

### ISSUE THREAD

**Issue by geraldmyres** [open-switch/opx-nas-interface#52]
Installed latest OPX 3.0.0.
 Have Ixia connected to e101-001-0 and e101-003-0 on S4048-ON.
 Populated /etc/network/interfaces with:
```
root@OPX:/home/admin# cat /etc/network/interfaces
# interfaces(5) file used by ifup(8) and ifdown(8)
# Include files from /etc/network/interfaces.d:
source-directory /etc/network/interfaces.d

auto e101-001-0
   iface e101-001-0 inet manual

auto e101-003-0
   iface e101-003-0 inet manual
```

Then:
```
 service networking restart
```

If I down/up interfaces, they come up. However, after rebooting switch, interfaces won't come up automatically. I have to cycle down/up again manually. Is this a bug or is there a procedure to do so?

**Comment by GarrickHe** [comment]
Investigating.

**Comment by atanu-mandal** [comment]
Hi @geraldmyres, can you please make sure the application stack does not bring those interfaces down after OPX comes up. e.g If you are running FRR and those ports are "shut" (not enabled) as part of startup config it will bring the interfaces admin down afterward. I have tried this steps on a VM running OPX 3.0.0 and it works fine (and I believe the same should work on any hardware platform). The interfaces (as configured in /ete/network/interfaces) are UP after reboot. 
Thanks,
-Atanu

**Comment by GarrickHe** [comment]
@geraldmyres @atanu-mandal , 

This is a service-file start-up issue. I am testing out a fix - which is going good - will submit a PR after I finish testing.

Thanks,
Garrick

**Comment by GarrickHe** [comment]
PR merged.

**Comment by geraldmyres** [comment]
Found that this fix only works when mtu is assigned.   Needs to work either way.

For example,  with following /etc/network/interfaces only e101-001-0 comes up after reboot:
### MTU assignments
auto e101-001-0
   iface e101-001-0 inet manual
   mtu 9184

auto e101-003-0
   iface e101-003-0 inet manual

**Comment by GarrickHe** [comment]
@geraldmyres 
I tested without any MTU assigned. I'll send you an email to discuss this further.
